### ISSUE TITLE
Chokes on file paths

### ISSUE THREAD

**Issue by danielbayley** [remarkjs/remark-defsplit#2]
~~~ markdown
<!-- README.md -->
## License
[MIT](LICENSE.md)
~~~
~~~ sh
> remark -u defsplit < README.md
<stdin>
  1:1  error  TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.parse (path.js:1515:5)
    at urlHost (/Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/remark-defsplit/index.js:92:15)
    at identifier (/Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/remark-defsplit/index.js:67:20)
    at forNode (/Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/remark-defsplit/index.js:46:25)
    at postorder (/Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/remark-defsplit/index.js:30:22)
    at /Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/flatmap/index.js:7:20
    at Array.forEach (native)
    at module.exports (/Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/flatmap/index.js:6:7)
    at postorder (/Users/Dan/Work/Projects/GitHub/Atom/hyperclick-octolinker/node_modules/remark-defsplit/index.js:28:25)

✖ 1 error
~~~

**Comment by wooorm** [comment]
Thanks for finding this, @danielbayley! Fixed, and released!
